# -*- coding: utf-8 -*-
"""circle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L98b7Vwx4O_lJPG1lERuzvHUNgwC2rxW
"""

pi = 3.14159
def area(radius):
    return pi*(radius**2)
def circumference(radius):
    return 2*pi*radius
def sphereSurface(radius):
    return 4.0*area(radius)
def sphereVolume(radius):
    return (4.0/3.0)*pi*(radius**3)