# -*- coding: utf-8 -*-
"""Factorial_via_iteration

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kco6WA4goEFs7TxSi5ztS3PA840a_Kiv
"""

def factI(n):
    result = 1
    while n > 1:
        result = result * n
        n -= 1
    return result

factI(4)